package instructions

import errs "github.com/gomatic/go-error"

// errNotAnExplainer marks a runner that carries no way to state its rules. It
// never leaves this package — it selects the "silent" column — but it is a
// value rather than a bare bool so the reason a check went unexplained stays
// nameable.
const errNotAnExplainer errs.Const = "runner states no instructions"

// preamble is the model an agent needs before any individual rule makes sense.
// This part IS stickler's to write: it describes stickler's own configuration
// and gating semantics, not any tool's rules.
const preamble = `# How this repository is checked

Generated by ` + "`stickler instructions`" + `. Each section below is the CHECK'S OWN
statement of what it enforces, asked of the tool that decides — not a copy kept
in stickler. Run it again after changing ` + "`.stickler.yaml`" + `: the sections
reflect the checks THIS repository actually runs.

## How to use this

Write code that satisfies these rules by construction. Reaching for
` + "`make check`" + ` to discover a violation means the cost is already paid: read
the sibling file first, write the contract before the body, and split a function
where the concept divides rather than where a number falls.

Never quote a threshold from memory. Every limit — complexity, coverage, file
length — is owned by the configuration, and a number restated in prose is a
second source of truth that loses the argument with CI. Read the config or run
the gate.

## What fails a build

- Any finding from a rule that is neither softened nor a probe.
- Any soft rule whose count has grown past its committed baseline.
- Any tool that failed to run at all — a crashed checker is never a clean pass.

A SOFT rule is reported but does not gate, and is capped by a per-rule baseline
in ` + "`.stickler.yaml`" + ` that may only fall. A rule with no baseline entry is
capped at zero. Softening is a rollout ratchet, not an exemption: raising a
baseline is a deliberate, reviewable decision, and the fix for a finding is the
finding's cause.

A PROBE is different in kind, and the difference is declared in the global
configuration rather than inferred from a count. A probe's precision is bounded
by judgment, not by syntax: it reports something for a person to adjudicate, so
it never gates, at any count, in any repository, and no baseline applies to it.
Its findings are still printed and still counted in the report — the remedy is
to adjudicate the finding or to fix the analyzer, never to record a number and
never to reword the prose the probe read. A repository cannot declare a probe of
its own; which rules are judgment-bound is a property of the analyzer.

## Adding a check

A tool is DATA. Its binary, arguments, config-file wiring, and output parser are
declared in ` + "`.stickler.yaml`" + `, never in Go. Adding a checker is
configuration, not a recompile.

## The rules
`
